#!/bin/sh

# Usage: build has_native

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1

add lib pkg/META		
add lib src/jsonm.mli
add lib src/jsonm.cmti
add lib src/jsonm.cmi
add lib src/jsonm.cmx
add lib src/jsonm.cma
add lib src/jsonm.a
add lib src/jsonm.cmxa
add lib src/jsonm.cmxs

add bin test/jsontrip

add doc README.md
add doc CHANGES.md
add doc test/examples.ml examples.ml
add doc test/jtree.ml jtree.ml

build
install jsonm
